### ISSUE TITLE
Multiple actions from a single click event

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/e28-spring20#10]
Hi everyone,

I was working off-forum with a classmate and the question came up about how to **trigger multiple actions/statements from a single click event**. I thought everyone might benefit from this info, so I wanted to echo the discussion here.

For an example, let's look at this v-on event from the lecture/notes:

```html
<button v-on:click='guesses.push(guess)'>Guess</button>
```

Imagine that in addition to adding the `guess` to the `guesses` array we also wanted to increment some `guessCounter` data property.

The value for the `v-on` directive takes a JavaScript expression, so if we wanted multiple statements to be executed as part of this expression, we could just add them - separating each statement with a semi-colon. For example:

```html
<button v-on:click='guesses.push(guess); guessCount++'>Guess</button>
```

This works for our rudimentary examples thus far, but would obviously grow convoluted as the complexity of our expressions grow. Also, it's not ideal to incorporate a lot of JavaScript logic into your HTML code.

The better solution would be to define a **method** (for example, `submitGuess`) in our Vue instance that could execute as many statements as we need, and invoke that method from the `v-on` directive:

```html
<button v-on:click='submitGuess'>Guess</button>
```

We'll see examples of methods this week (4) when we dig deeper into event handling.

**Comment by csci50-cbutler** [comment]
FYI, I used a comma and it worked.  Could that be a problem going forward?  Here is my screen shot.

![image](https://user-images.githubusercontent.com/47401514/74798008-665f4580-5281-11ea-8747-358fd4270e03.png)

Cecilia

**Comment by susanBuck** [comment]
Hi @csci50-cbutler -

That approach is using JavaScript's **comma operator**:

> The comma operator evaluates each of its operands (from left to right) and returns the value of the last operand. -ref: [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Comma_Operator)

Example (also from [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Comma_Operator)):

```js
let x = 1;

x = (x++, x);

console.log(x);
// expected output: 2

x = (2, 3);

console.log(x);
// expected output: 3
```

It works in your example because each of the operands are evaluated from left to right, with the third operand being returned:

1. `addItem = true` (evaluated)
2. `shoppingList.push(item)` (evaluated)
3. `count+=1` (evaluated and returned)

But in this use case, what is returned is irrelevant. The `v-on` directive is not assigning or expecting any values to be returned - it's just executing the inline statements you give it.

**All that explanation aside: I don't anticipate it causing problems. : ) That being said, I think the semi-colon is a more logical separator to use.** (At least until we outsource the statements to methods.)

**Comment by csci50-cbutler** [comment]
Thank you Very helpful.
