### ISSUE TITLE
Final Project 3 Expectations Clarification (Placeholder Text?)

### ISSUE THREAD

**Issue by guyewhite** [susanBuck/e28-spring20#102]
Hi @susanBuck, 

My Project 3 helps doctoral candidates choose the right statistical tests for their research.

**Question:** For final submission of Project 3, is it permitted to have placeholder text (lorem ipsum...) populating the statistical test descriptions and details? Before I launch this to my prospects/clients, I will need to do that work of completing that text -- but is it sufficient for the purposes of Project 3 to simply have the placeholder text there?

**Comment by susanBuck** [comment]
Yes, that's sufficient. 👍

**Comment by guyewhite** [comment]
Thank you.
