### ISSUE TITLE
Vuex Store is not accessible through computed property in App.vue

### ISSUE THREAD

**Issue by oscarxiao** [susanBuck/e28-spring20#104]
Hi Guys,
Here is my Vuex store file
<img width="324" alt="Screen Shot 2020-05-11 at 10 07 20 PM" src="https://user-images.githubusercontent.com/40640721/81640607-d0e0d700-93d3-11ea-9c58-f9275fa54a50.png">
Here is how I import and register my Vuex Store. 
<img width="562" alt="Screen Shot 2020-05-11 at 10 08 04 PM" src="https://user-images.githubusercontent.com/40640721/81640642-e950f180-93d3-11ea-9567-68629dbb98f5.png">
I try to use it in the computed property
<img width="340" alt="Screen Shot 2020-05-11 at 10 09 24 PM" src="https://user-images.githubusercontent.com/40640721/81640713-1f8e7100-93d4-11ea-8fc3-5b5e8d61cf02.png">
and render it by {{expCount}}
The inspector will show me an error saying "can not read property 'state' of undefined"
<img width="1458" alt="Screen Shot 2020-05-11 at 10 10 42 PM" src="https://user-images.githubusercontent.com/40640721/81640793-54022d00-93d4-11ea-8832-e83c6f1e56a5.png">
Any ideas?

**Comment by oscarxiao** [comment]
if I don't render expCount, I just look into the vue inspector, in the computed section. This will show. 
<img width="545" alt="Screen Shot 2020-05-11 at 10 18 52 PM" src="https://user-images.githubusercontent.com/40640721/81641265-734d8a00-93d5-11ea-8d8b-24a058c80c5e.png">

**Comment by susanBuck** [comment]
Hi @oscarxiao - 

Confirming you resolved this issue and don't need additional assistance? I see the post was closed, but you didn't note a resolution. 

I've had students inadvertently close posts in the past so I just wanted to double check. : )

**Comment by oscarxiao** [comment]
Yes, @susanBuck. I resolved it. Thanks. 
---
> Hi @oscarxiao -
> 
> Confirming you resolved this issue and don't need additional assistance? I see the post was closed, but you didn't note a resolution.
> 
> I've had students inadvertently close posts in the past so I just wanted to double check. : )
