### ISSUE TITLE
Netlify is required for P3?

### ISSUE THREAD

**Issue by maqboolk** [susanBuck/e28-spring20#105]
Do we need to use Netlify for our final project (p3)?

**Comment by ShBodden** [comment]
Yes, it is required 


Requirements
Your P3 should meet all the same specifications as P2, with the following additions:

State management w/ Vuex
At least one data entity of your app should be managed via a Vuex store
Testing
At least one passing unit test
Passing E2E testing for all features
Form validation using Vuelidate
Deployed on Netlify with a custom domain of http://e28p3.yourdomain.com (https is optional but suggested)
Optionally, you are encouraged but not required to implement a feature in your application that utilizes local storage.

**Comment by maqboolk** [comment]
@ShBodden Thanks, I missed that requirement.
