### ISSUE TITLE
Testing graphics with Cypress

### ISSUE THREAD

**Issue by tmussa1** [susanBuck/e28-spring20#111]
I have incorporated graphics like charts and datepickers in my projects. I couldn't come across a straight forward way to test those. I don't think I have enough time before the deadline. Is it okay to omit them or does anyone have good resources? Here is my git repo https://github.com/tmussa1/p3

**Comment by susanBuck** [comment]
Quick reply just to say it’s okay to omit them.

**Comment by susanBuck** [comment]
Re: resources for testing things like charts - perhaps: https://docs.cypress.io/guides/tooling/visual-testing.html
