### ISSUE TITLE
P1 - preparation questions

### ISSUE THREAD

**Issue by DoryAzar** [susanBuck/e28-spring20#12]
The P1 requirements indicate that we should keep a history of the different rounds. @susanBuck is the expectation to have a full history constantly visible in the UI or could we limit to showing only the last 2 rounds?

**Comment by susanBuck** [comment]
You could limit it if you'd like - just as long as there's some tracking of previous iterations.

Also, just to be clear - it's not expected the round history will persist with a page refresh (We'll get into that later in the semester.)
