### ISSUE TITLE
Week 4 Assignment: Question 7

### ISSUE THREAD

**Issue by smaaliki** [susanBuck/e28-spring20#14]
Hi, 

Question 7  has 3 options.  Two of them are the same.
![Wk4 Q7 issue](https://user-images.githubusercontent.com/35793409/75056151-d70b9980-54ef-11ea-8423-8a9f2045bfc4.png)

**Comment by susanBuck** [comment]
They're different - it's just subtle. 

Note the different order of "modifier" and "argument", as well as the different separators - colon vs. period.

**Comment by smaaliki** [comment]
Hehe.  I either need more sleep or new glasses! Thanks for the clarification.

**Comment by susanBuck** [comment]
np! It's easy to miss. : ) I'm going to change the font on the answers to monospaced and bump up the size to make it clearer.
