### ISSUE TITLE
Week 2 Assignment - JS Game showcase

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/e28-spring20#17]
Hi everyone,

I wanted to take a moment to highlight some of the interesting games your classmates built for the Week 2 JS practice assignment.

+ [Typing speed](https://jsfiddle.net/fe89bdxp)
+ [Tic Tac Toe](https://jsfiddle.net/peryan77/jmuwt9rc)
+ [Mastermind](http://mastermind.punggolgp.com.s3-website-ap-southeast-1.amazonaws.com/) ([Instructions](https://github.com/punggolzenith/e28/tree/master/game))
+ [Acey Deucey](https://jsfiddle.net/ambielecki/o6n5wbtx)
+ [Memory Game](https://jsfiddle.net/vthilagar/7yju8nsd/8)
+ And a few Mystery Word games: [1](https://jsfiddle.net/Dory/nvd53c7m), [2](https://jsfiddle.net/kugdhw3x/11), [3](https://jsfiddle.net/fgp37oud)

**Comment by RobertHolzhauser** [comment]
Great job everyone!!
