### ISSUE TITLE
setInterval() timer and accessing Vue element properties

### ISSUE THREAD

**Issue by vthil3049** [susanBuck/e28-spring20#19]
I was trying to do something like shown in this page with setInterval(), except that I'm trying to access the Vue element's data properties instead of the document element properties used in this example.
https://www.w3schools.com/howto/howto_js_countdown.asp.

Within the context of  setInterval's function, it does not seem to work, since access to 'this' is not there.
```
var x = setInterval( function(){
// all the code that calculates the time
//
    this.timing = seconds;  //this is not working
}), 1000);
```

So, do I have to generate a custom event to propagate data from setInterval() or how would that work?
Thanks for any suggestions.
Vani

**Comment by DoryAzar** [comment]
Javascript closures... they could be messy sometimes. As you can see `this.timing` is in the scope of a closure function of set interval so `this` does not refer to the vue instance anymore as you would expect. 

However if you do  `nameofyourvueinstance.timing` it might actually work. So if your Vue instance is called `app` then you can do `app.timing.` If this still doesn’t work, then your safer bet would be to go all the way to the window root and refer to it as `window.app.timing`.

That is how I would approach with my lack of knowledge of the full features of Vue. Perhaps Vue has its own set of methods to help you achieve the same thing.

**Comment by susanBuck** [comment]
@DoryAzar is correct about referencing `timing` via the `app` instance:

Example:
```js
var x = setInterval(function () {
    console.log(app.timing);
}, 1000);
```

Alternatively, you could use JavaScript arrow functions - because they don't have their own execution context the `this` is inherited:

```js
var x = setInterval(() => (
    console.log(app.timing)
), 1000);
```

Finally, another solution is to create a variable that references the correct scope prior to the setInterval:
```js
let self = this;
var x = setInterval(() => (
    console.log(this.timing)
), 1000);
```

More on this topic:
https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setInterval#The_this_problem

**Comment by vthil3049** [comment]
Thank you Dory and Susan!
