### ISSUE TITLE
Week 5 Word Scramble - External libraries and avoiding repeat words

### ISSUE THREAD

**Issue by ShBodden** [susanBuck/e28-spring20#23]
Hi Prof. Buck

While working on this week's assignment I ran into some issues. I'm not the best programmer and I was trying to implement the Fisher-Yates shuffle on my own to scramble the word. I was wondering if it's ok for these assignments and projects to utilize something like Lodash or other libraries to perform this function without violated any class rules? 

I'm also stuck on not getting my word to be used twice in a row. Can someone point me in the right direction? 

Currently I'm generating a random number and using that as an index for my words array.

**Comment by susanBuck** [comment]
Hi @ShBodden -

Yup, it's okay to pull in utilities like lodash if you'd like. 

It's also okay to use online resources to find code to help with tasks like these. For example - perfectly acceptable to Google something like "javascript shuffle characters in word" and adapt solutions you find. Of course, this is assuming you take the time to dissect the solution and understand what it's doing.

**Regarding not getting the same word to be used twice in a row:**

Here are some hints:

One thing you'll want to do after picking a word, is set up a data property to record what that word was, e.g. `lastWord`. This way, the next time you pick a word, you can check it against the `lastWord` and make sure it's not a match. If it is a match, you should pick a new word.

In my solution (which I'll share in tomorrow's lectures), I used a **while loop** to accomplish this. 

Here's an abbreviated preview of that within a method I'm using called `loadGame`:

```js
loadGame: function () {
 
    // This while loop will run as long as this.word === this.lastWord
    // in other words - until we find a word that does not match the last word
    while (this.word === this.lastWord) {
        // Code here to assign `this.word`...
    }
    
    // Record the `lastWord` so that the next time we invoke this function we don't use the same word
    this.lastWord = this.word;
}
```
