### ISSUE TITLE
Independent Study - Milestone 1 (for Certificate?)

### ISSUE THREAD

**Issue by mohdmunsif** [susanBuck/e28-spring20#25]
Hi. I am not sure which one i qualifies in, I'm not an undergrad (already have my undergrad degree) but technically not a postgrad too. I am taking this as part of a certificate that i want to complete - so would this also be required for a certificate from HES?

**Comment by susanBuck** [comment]
Hi @mohdmunsif - According to my records, you are registered in this course for "graduate credit". 

Given this, you should go ahead and complete the independent study milestones. 👍

**Comment by mohdmunsif** [comment]
got it, thank you
