### ISSUE TITLE
Free Weekend Access to VueMastery.com  March 13 - 15

### ISSUE THREAD

**Issue by RobertHolzhauser** [susanBuck/e28-spring20#28]
Hey Everyone,

I happened to see that VueMastery.com is making all of their courses available for free next weekend, March 13 - 15.  Here's the link: [https://www.vuemastery.com/free-weekend/](url)  

I don't know anything else about it, but it looks like a good supplementary resource, so I thought I'd share.

Have a great day!
Robert

**Comment by procchio77** [comment]
Thanks Robert! I definitely will take advantage of this.  I am enjoying Vue more and more.

**Comment by susanBuck** [comment]
Thanks for sharing!

**Comment by angyts** [comment]
Yay thanks @RobertHolzhauser  These were the videos that got me hooked on `Vue.js`. 

The cool serenading voice. And the hey bros, this is so easy attitude! And it was too good that I finished all my project specifications with just the basic videos... Hence I'm back here...

**Comment by csci50-cbutler** [comment]
Fantastic.  Thank you!!!

**Comment by jaggedaz** [comment]
Another great resource for Vue materials is Frontend Masters (frontendmasters.com).  We actually get 6 months free if you signed up for the GitHub Student Developer Pack that was mentioned earlier in the course.

**Comment by csci50-cbutler** [comment]
Thanks!  Really helpful!!!
