### ISSUE TITLE
Question About Production Server - Ok to use DreamHost/FTP?

### ISSUE THREAD

**Issue by hakanovski** [susanBuck/e28-spring20#29]
Hello,

Can I upload my projects and further assignments to my personal website and share the URL for Project 1 submission?

Last week I setup my production server over Digital Ocean and got my domain from namecheap.com but while I was uploading my assignment last week I thought there are many steps. My url is - http://hakanyorganci.me/

I have been using DreamHost for a while and so far I have uploaded my various projects to my personal website over their Web FTP. Last week I uploaded my assignment [Word Scramble Game](https://www.hakanyorganci.com/hknyrgnc/e28_word_scramble.html) to my [personal website](https://www.hakanyorganci.com/hknyrgnc/dgmd_e_28.html). I hope I can continue to do like this.

**Comment by angyts** [comment]
Yeah, sometimes I get so lazy with static sites, I just drop them at a S3 bucket with static site hosting. Then connect it to cloudflare DNS... But i guess, probably that's the point. For us to get yucky and into the nuts of a server (SSH and apache yikes!).

**Comment by susanBuck** [comment]
Hi @hakanovski -

I agree, the setup I showed is a bit more involved than a simple shared host with FTP transfer. : )

But I would only ever suggest a simple shared host with FTP transfer for a simple static site without real-world users. For example, a personal portfolio. 

Any sort of site with a user base needs a more robust infrastructure, and in this course I want us to design our applications with that in mind.

At the very least, I recommend any project be tracked with a version control system such as Git. Does your DreamHost account support Git? Furthermore, in Week 8 we'll introduce build systems and that will require NPM (Node Package Manager) - also something you'll need to run on your production server.

There are many other command line type utilities you'll find yourself using on a production server - from deployment scripts to continuous integration to some automated testing.

Finally, later in Week 13, I'll introduce static site hosting, which can take some of the complexity out of the VPS system we're using, but it has its limitations as well, and we'll be comparing/contrasting the two.

My suggestion is to continue to work with the infrastructure I'm showing. You already know how to FTP to your shared host - why not use this as an opportunity to get comfortable with something more advanced that's used on real-world applications? : )

**Comment by hakanovski** [comment]
Thanks for the detailed answer.

**Comment by hakanovski** [comment]
ok I uploaded word scramble game to my static - http://week-5-assignment.hakanyorganci.me/
