### ISSUE TITLE
Ignore .DS_Store with git on Mac

### ISSUE THREAD

**Issue by guyewhite** [susanBuck/e28-spring20#3]
Hi Beautiful Team,

Is there a way to globally set git's command line tool to ignore .DS_Store?  If not, what is the most efficient way for it to ignore these files for the e28 repository we are building this week?

I've looked at numerous articles on StackOverflow and on GitHub, but I'm seeing many inconsistent responses and I've found nothing that persists globally as mentioned above.

Thanks for your help.

Guy
Portland, Oregon

**Comment by DoryAzar** [comment]
you can add a .gitignore file into your folder(s) and then add the line “.DS_Store” to it.

If you already pushed the DS store file though, you might first need to delete it. sync your repo and then add the .gitignore.

**Comment by susanBuck** [comment]
Piggy-backing on @DoryAzar's answer, after you've added `.DS_Store` to your `.gitignore` file, you'll need to tell git to stop tracking that file by removing it from the index.

You can do that with this command:

```
git rm --cached .DS_Store
```

This is only required for files that have been tracked and then were added to `.gitignore`. If you create a new file you don't want to track and immediately add it to `.gitignore` before it gets committed, you don't have to worry about this step.

**Comment by guyewhite** [comment]
Hi Everyone. @DoryAzar and @susanBuck thank you for your answers. Here is the all-encompassing solution that ended up working best:

1. I opened Mac Terminal.

2. I navigated to my documents folder by doing the following commands (without the $):

`$ cd /`

`$ cd Users/myUserName/Documents`

3. I then made a directory for my githubpresets:

`$ mkdir githubpresets`

4. I then navigated to that director:

`$ cd/githubpresets`

5. I then made a file called .gitignore_global:

`$ touch .gitignore_global`

6. Then, I edited the file using nano:

`$ nano .gitignore_global`

7. Within this file, I added these contents provided by GitHub: [https://gist.github.com/octocat/9257657](https://gist.github.com/octocat/9257657)

8. I then added this file to be implemented globally: 

`$ git config --global core.excludesfile ~/.gitignore_global`

(Optional) As @susanBuck suggested, I also ran the following command while inside the appropriate repository folder as I had already accidentally uploaded .DS_Store:

`$ git rm --cached .DS_Store`

Hope this helps all of you :) Thanks for your help in getting this all put together.

**Comment by susanBuck** [comment]
Showing how to make a global gitignore file is a neat approach; thanks for sharing the details with everyone @guyewhite!

**Comment by angyts** [comment]
**OMG** @guyewhite :heart_eyes: :heart_eyes:

What a great idea, I've never learnt of this `.gitignore_global` until now.

And this is after i've made a super duper noob mistake of **committing credentials/passwords** to a git repository...

I would totally recommending adding the following to save yourself some trouble (or shame) like me.

```
# .gitignore
...

# Things to exclude so that you won't be caught with your underpants like me #
.key
.env
db.sqlite3
credentials.json
.password

```

Oh yes, before I forget, I tend to use a wide spread of technologies and I get lazy. So there is [this amazing gitignore generator](https://www.gitignore.io) that does some of the heavy lifting.
