### ISSUE TITLE
Function in method ran before triggering the event listener

### ISSUE THREAD

**Issue by oscarxiao** [susanBuck/e28-spring20#30]
I can see the null value in my console twice everytime I reload the page. I don't understand why.
-----------------------------------------
```js 
let app = new Vue({
  el: "#app",
  data: {
    userName: "Oscar"
  },
  methods: {
    clearOutUser: function() {
      this.userName = null;
      console.log(this.userName);
    }
  }
});
```

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Shopping list</title>
    <meta charset="utf-8" />

    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js" defer></script>
    <script src="script.js" defer></script>
  </head>

  <body>
    <div id="app" v-cloak>
      1. <input type="text" v-model="userName" />
      {{userName}}
      <br />
      2. <input type="text" v-model="userName" :keyup.enter="clearOutUser()" />
    </div>
  </body>
</html>
```

**Comment by ambielecki** [comment]
It should be @keyup.enter (@ is the shortcut for v-on, : is the shortcut for v-bind).  Don't know nearly enough about Vue's internals to know what happens when you try to bind that to a function

**Comment by oscarxiao** [comment]
Thank you @ambielecki

**Comment by angyts** [comment]
I tried running it locally. Seems a bit wierd. But after I removed the `defer` from the vue source code line it seems to work fine.

`<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>`

**Comment by susanBuck** [comment]
@oscarxiao - If @ambielecki's tip solved this problem can you confirm by closing this post? If not, feel free to keep it open and follow-up with details about what's still not working. : )
