### ISSUE TITLE
Font awesome CDN icon doesn't show

### ISSUE THREAD

**Issue by oscarxiao** [susanBuck/e28-spring20#33]
I linked my font awesome cdn using this inside my<head> tag
```html
<link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    />
```
and inside the body 
```html
<div class="computersChoice" v-if="playerFullName">
        <ul>
          <li>
            <span><i class="fa fa-hand-rock"></i>Rock</span>
          </li>
          <li>
            <span><i class="fa fa-hand-paper"></i>Paper</span>
          </li>
          <li>
            <span><i class="fa fa-hand-scissors"></i>Scissor</span>
          </li>
        </ul>
      </div>
```
but those icon didn't show!!!!

**Comment by ambielecki** [comment]
Looks like you've got the wrong class, at least for rock, there's only a non-filled version of that icon. `<i class="fa fa-hand-rock-o" aria-hidden="true"></i>`

<https://fontawesome.com/v4.7.0/icon/hand-rock-o>

**Comment by susanBuck** [comment]
I believe the hand icons are only available in FontAwesome v5, so update your style link to:

```html
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" />
```

Then the icons as you've written them should work.

**Comment by oscarxiao** [comment]
Thank you, Professor @susanBuck It works.
----------------
> I believe the hand icons are only available in FontAwesome v5, so update your style link to:
> 
> ```
> <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" />
> ```
> 
> Then the icons as you've written them should work.
