### ISSUE TITLE
Anyone knows any good online resource for Ajax?

### ISSUE THREAD

**Issue by maqboolk** [susanBuck/e28-spring20#39]
Hi All,

Week 10 is about Ajax API. I was wondering if anyone knows any good online resource/s where i can learn Ajax step by step? I am new to Ajax and I want to start looking into it from now so by  week 10 I am Ajax PRO. 

Thanks 
Maqbool

**Comment by maqboolk** [comment]
Found something online. Here is the link if anyone interested.
https://developer.mozilla.org/en-US/docs/Web/Guide/AJAX/Getting_Started

**Comment by csci50-cbutler** [comment]
FYI:  W3Schools.com and Tutorialspointcom has some helpful content.  W3schools has separate AJAX sections for javascript, xml & PHP.  I also think Udemy may have some hands-on training as well.

Here's the link to Tutorialspoint.
https://www.tutorialspoint.com/ajax/index.htm

**Comment by maqboolk** [comment]
@csci50-cbutler  Thank you

**Comment by angyts** [comment]
I am not a pro, but I've used simple Ajax for some of my previous projects, and I think the best is still to get some hands on...

When doing debugging and testing I found this app called `postman` extremely useful.

**Comment by maqboolk** [comment]
@punggolzenith Thank you.
