### ISSUE TITLE
ANNOUNCEMENT: Change to weekly assignment grading configuration

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/e28-spring20#4]
Hi everyone,

I'm writing to announce a change in how weekly assignments are configured (starting in Week 2).

In past semesters, I had it configured so you could submit an assignment multiple times but it was always your *latest* submission that was the recorded grade. This allowed students the opportunity to preview an assignment early in the week.

This configuration was occasionally problematic because students would sometimes accidentally open the assignment after they had made their "final" attempt, and it triggered a new submission they did not intend to make.

I thought the best way around this was to configure the assignments so that your *highest* score was the one that was recorded. That way, if you inadvertently opened the assignment, you could submit it with no answers, knowing the 0 score would be disregarded.

What I naively failed to think about is how students could game this configuration - if a student is unsure of an answer to a question, they could just submit the assignment multiple times with each potential answer selected, and then let the highest scoring assignment "win." This technique might boost one's grade, but it hinders my ability to see what concepts students are struggling with and assign grades that honestly reflect each student's performance/understanding. 

**Because of this, starting with the Week 2 assignment and moving forward, it will always be your *latest* attempt that will be recorded. You will still be allowed to make multiple attempts so that you can review the assignment early in the week.** 

-Susan

**Comment by guyewhite** [comment]
Thanks, @susanBuck ! Canvas is a funny animal ;)

**Comment by susanBuck** [comment]
@guyewhite Truer words have never been spoken. :)

**Comment by guyewhite** [comment]
@susanBuck , after attempting a submission right now, (leaving out the answer to the first question) it does not auto-grade or provide a score for the remainder of the quiz submission. Accordingly, I was hoping to see if I scored 40 (without the final 10 points for the first question). Am I to interpret your comments above to mean that we will NOT be able to preview our score in advance any more? (As I ask this, I'm feeling my own Canvas pains that I've experienced as an instructor)

**Comment by susanBuck** [comment]
Hi @guyewhite - 

It shouldn't show you any auto-grading right after submission. (If it did, one could just continue to make new submissions until you got the full points for the auto-gradeable questions).

>> Am I to interpret your comments above to mean that we will NOT be able to preview our score in advance any more?

Correct, you will NOT be able to preview your score in advance. But this shouldn't be new. Was it something you were able to see in Week 1? 

For reference, here's the option on my end:
![image](https://user-images.githubusercontent.com/237711/74060338-c28bb500-49b7-11ea-8149-d6987b21b8dc.png)

The assignments are all set to that (unchecked), until I complete grades, at which point I check it off so that you're able to review your answers. 

Does that make sense?

**Side note**: I appreciate your input/hearing what the students see on their end (especially as someone who has experience on the instructor side of things as well). I try and use the the "Student View" simulation to test things - but it's not always perfect/accurate.

**Comment by guyewhite** [comment]
Hi @susanBuck ,

Indeed I could see during the first week that I had a score of 39 prior to you grading the open-response questions. However, when I navigate back to the Week 1 quiz today, it's been "muted". Earlier last week, it was not like that.

Accordingly, that set a bit of an expectation in my head for future weeks :) Now I know what to expect. 

I'm very much looking forward to deploying some useful single-page applications to my clients. What I'm learning in this class will be put in near-immediate use. Peace.

**Comment by susanBuck** [comment]
It's entirely possible the muting was something I failed to have set at start, which would explain the difference.

Thanks again for the note!

**Comment by csci50-cbutler** [comment]
So there is no way to see how you've faired until after the submission now.  There was a score in Assignment 1.  If I understand correctly, there should not be one...

**Comment by susanBuck** [comment]
@csci50-cbutler That's correct - scoring information is not/should not be revealed automatically. 

It should only be revealed after I've gone through the assignments, graded any open-ended questions, and posted the grades.

Auto-scoring information may have been visible in Week 1, but this was not intentional and should not happen on future assignments.

Adding to all of this, I should mention that the assignments are not intended to be exceptionally challenging. They're just designed to keep everyone on track, reviewing the information covered that week. **Students who watch the lectures, read the notes, and do the work typically consistently earn A's on the assignments.** All this to say, don't overthink them/stress about it too hard. Give it your best shot, submit your work, and move forward. Once the grades are released, if you have questions about an answer you missed, don't hesitate to reach out. I'm always happy to review questions with students and calibrate for future assignments if you're not performing as high as you'd like.

**Comment by csci50-cbutler** [comment]
Thank you.
