### ISSUE TITLE
Webpack really necessary?

### ISSUE THREAD

**Issue by maqboolk** [susanBuck/e28-spring20#41]
Hi Susan,

You mentioned in lecture that Webpack is complex and hard to configure. Can we achieve same results with something else that is not complex, easy to configure? 

Laravel is the solution to webpack, but it is a layer on top of webpack. 

Is there something else that does not use Webpack behind and uses something else?

**Comment by susanBuck** [comment]
Yup, there are alternatives to webpack.

Here's a useful discussion on reddit relevant to this: [What are the best alternatives to webpack?](https://www.reddit.com/r/Frontend/comments/ak95x3/what_are_the_best_alternatives_to_webpack_in_2019/)

My takeaways from this discussion:
+ Webpack is currently "king" in terms of module bundlers.
+ There are simpler module bundlers, but they may not be as powerful webpack; could meet your needs though.
+ Webpack is complex, but tools like and Laravel Mix (discussed in week 8) and Vue CLI (to be discussed in Week 9) simplify it.

If anyone in the class has experience with other module bundlers they've used/like, feel free to share!
