### ISSUE TITLE
Lock Files

### ISSUE THREAD

**Issue by maqboolk** [susanBuck/e28-spring20#42]
Hi Susan, 

Lock file stores the last run version number on our local and it is used in production, but what if more than 1 developer are working on the project and versions are different in each local? 

What will happen in that case?
Is there a process to sync lock files or developers communicate with the team and update dependencies manually on their local so everyone is on same page?

**Comment by susanBuck** [comment]
Conflicts in the lock file are addressed like any other code conflicts you might see from a team of developers working on the same code base.

Most importantly, with a version control system like Git in place, it will let you know when there are merge conflicts (e.g. you try to push version 1.2.3 of some dependency while your teammate has already pushed version 1.2.4).

At that point, you communicate with your teammate to decide which version should be used. : )

**Comment by maqboolk** [comment]
Thank you Susan
