### ISSUE TITLE
Vue CLI Install Error

### ISSUE THREAD

**Issue by hakanovski** [susanBuck/e28-spring20#44]
After entering "$ npm install -g @vue/cli" in Terminal, I am getting 3142 Error. I checked the forums, logs but could not debug it.

npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! Unexpected end of JSON input while parsing near '...nes":{"node":">=6"}},'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Hakan/.npm/_logs/2020-04-05T03_29_53_319Z-debug.log

I tried to clean the cache with npm cache clean --force and tried to install Vue CLI but after that I got bunch of different errors below.

Any idea?

npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /usr/local/lib/node_modules
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!  [Error: EACCES: permission denied, access '/usr/local/lib/node_modules'] {
npm ERR!   stack: "Error: EACCES: permission denied, access '/usr/local/lib/node_modules'",
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Hakan/.npm/_logs/2020-04-05T03_42_36_149Z-debug.log

**Comment by hakanovski** [comment]
I entered command with root/adm sudo and now I installed the Vue CLI.

"sudo npm install -g @vue/cli"

Looks like I resolved the issue.

**Comment by susanBuck** [comment]
Glad you found the solution, @hakanovski. : )

Here's a command to adjust the permissions of your computer's main `node_modules` directory:

```bash
sudo chown -R $USER /usr/local/lib/node_modules
```

That should prevent you from having to prefix future `npm` commands with `sudo`.

**Comment by vthil3049** [comment]
Susan,
I still have this problem when I try to install vue/cli. It seems fine in the beginning, but it ends with gyp configure ERR.
Pasting below:

```
`> fsevents@1.2.12 install /usr/local/lib/node_modules/@vue/cli/node_modules/fsevents
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/@vue/cli/node_modules/fsevents/build'
gyp ERR! System Darwin 19.3.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/@vue/cli/node_modules/fsevents
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules/@vue/cli/node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ @vue/cli@4.3.0
updated 1 package in 30.356s
~   $ 
```

**Comment by susanBuck** [comment]
Hi @vthil3049 - Can you show the full output including the original command prefixed with `sudo`?

**Comment by susanBuck** [comment]
Note: Going to move all future conversations re: @vthil3049's last post to this thread: https://github.com/susanBuck/e28-spring20/issues/46
