### ISSUE TITLE
npm run serve - cant access locolhost

### ISSUE THREAD

**Issue by maqboolk** [susanBuck/e28-spring20#45]
Hi All,

After Running `npm run serve`, I am not able to access Local URL but i can access Network URL.
Any Idea why I cant access Local URL and how can i Fix it? 

```

  App running at:
  - Local:   http://localhost:8080/ 
  - Network: http://192.168.0.13:8080/
```

Thanks

**Comment by susanBuck** [comment]
Hi @maqboolk - Few questions:

1. Mac or Windows?
2. Can you share a screenshot of what you see in the browser?
3. Are you running any anti-virus programs?

**Comment by maqboolk** [comment]
Hi Susan,

1. I am on Mac
2. I see this when I try to use Local URL
![image](https://user-images.githubusercontent.com/3629441/78516042-2cd98f80-7786-11ea-90b1-8671047ca45f.png)
3. I have ESET Endpoint Antivirus on my machine

Thank you

**Comment by susanBuck** [comment]
Hi @maqboolk - Thanks for these extra details.

Could you try disabling ESET Endpoint Antivirus and restarting the server/seeing if localhost:8080 works then? 

If it does, we can assume that's the source, and moving forward you can just use the network URL.

**Comment by maqboolk** [comment]
Hi @susanBuck - 

Local URL(localhost:8080) worked after disabling the Antivirus Software on my machine.

I will use Network URL instead of Local.

Thanks for your help

**Comment by maqboolk** [comment]
Hi @susanBuck 

I tried adding different port( --port 2020) in **package.json** file and I am able access Local URL without disabling Antivirus.

```
  "scripts": {
    "serve": "vue-cli-service serve --port 2020",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
```

**Comment by susanBuck** [comment]
Gotcha, so the anti-virus program seemed be be blocking port 8080. 

Glad it's resolved. 👍
