### ISSUE TITLE
gyp ERR during vue cli install

### ISSUE THREAD

**Issue by vthil3049** [susanBuck/e28-spring20#46]
Susan,
I followed all the rules to install Vue cli as per your notes on my Mac. I changed ownership of the node_modules folder as you mentioned in the Vue CLI section of your notes.

I got this problem when I try to install vue/cli. It seems fine in the beginning, but it ends with gyp configure ERR. After this, it lets me create a new Vue starter project, but was wondering if this will create problems down the road.

Please advise.
Thanks
Vani

Pasting error below:
```
**`_> fsevents@1.2.12 install /usr/local/lib/node_modules/@vue/cli/node_modules/fsevents

node-gyp rebuild

gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/@vue/cli/node_modules/fsevents/build'
gyp ERR! System Darwin 19.3.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/@vue/cli/node_modules/fsevents
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules/@vue/cli/node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 install: node-gyp rebuild
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

@vue/cli@4.3.0
updated 1 package in 30.356s
~ $_**
```

**Comment by DoryAzar** [comment]
I had the same thing. Since it is a global system installation just precede the command with a "sudo" and you should be good to go.

**Comment by vthil3049** [comment]
Hi Dory, 
I did try 

```
sudo npm install -g @vue/cli
```

It still gave me an error

Maybe I have to manually rebuild gyp too the same way?

```
sudo node-gyp rebuild
```

**Comment by DoryAzar** [comment]
Hmmm I am noticing something else here. Did you have node from before? It is looking like you have version 10.16. I would suggest upgrading node. The newest is now 13.x.x.
You probably should start there.

**Comment by susanBuck** [comment]
Adding to @DoryAzar's suggestions, it also looks like your `node-gyp` is at version `3.8.0`, while the latest version is `5.1.0` so it'd be a good idea to update that as well.

Not saying with confidence that updating will fix this, but as @DoryAzar noted, it's a good place to start, and it won't hurt.

Also, can you share the output of `/usr/local/lib/node_modules/` so we can see the permission details of your `node_modules` directory?

**Comment by vthil3049** [comment]
Hi Susan, Dory and all,
My apologies - since I'm 'at work' right now, I won't be able to get to doing this until later this evening.
I'll send you the outputs before 7pm this evening. Once again, my apologies, since we're swamped at work.
Thanks for understanding.
Vani

**Comment by susanBuck** [comment]
@vthil3049 - Understood and no rush. : )

**Comment by vthil3049** [comment]
Thank you Dory and Susan. Yes, I did have node from before, because I was running Angular.
This is the output of ls in the node_modules:

```
/Applications/XAMPP/htdocs/e28/practice/week9 (master) ! $ ls /usr/local/lib/node_modules
@angular	@vue		node-gyp	nodemon		npm
/Applications/XAMPP/htdocs/e28/practice/week9 (master) ! $ ls -l /usr/local/lib/node_modules
total 0
drwxrwxrwx   3 vani  wheel   96 Dec 29 18:22 @angular
drwxrwxrwx   3 vani  wheel   96 Apr  5 23:46 @vue
drwxrwxrwx  17 vani  wheel  544 Jan  1 20:52 node-gyp
drwxrwxrwx  12 vani  wheel  384 Jul 18  2018 nodemon
drwxrwxrwx  25 vani  wheel  800 Jun  1  2019 npm
/Applications/XAMPP/htdocs/e28/practice/week9 (master) ! $ 
```

I'll try upgrading the node version and let you know how it goes next.

**Comment by vthil3049** [comment]
Finally a breakthrough! Thanks Susan and Dory!
I reinstalled node through homebrew and followed the same set of instructions again.

This time, I finally was able to install the vue cli without gyp errors:

```
$ npm  install -g @vue/cli
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
/usr/local/bin/vue -> /usr/local/lib/node_modules/@vue/cli/bin/vue.js

> fsevents@1.2.12 install /usr/local/lib/node_modules/@vue/cli/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
+ @vue/cli@4.3.0
added 70 packages from 33 contributors and updated 1 package in 33.065s
~   $_ 
```

**Comment by susanBuck** [comment]
Excellent - glad it's all sorted out! : )
