### ISSUE TITLE
Week 9 Canvas typos

### ISSUE THREAD

**Issue by nicholsonjf** [susanBuck/e28-spring20#47]
See the two red boxes in the attached screenshot. There's a "showed" that should be "shown" and (unless I'm missing something) a "p4" that should be "p3".

Cheers!

<img width="1439" alt="week9" src="https://user-images.githubusercontent.com/4286084/78627438-6f22cf80-785f-11ea-8144-9063852cd7c9.png">

**Comment by susanBuck** [comment]
@nicholsonjf Thanks for the head's up - correcting now!

**Comment by susanBuck** [comment]
I just realized you made this post in my e28 course forum, but your post is relevant to my e15 course.

Any ideas how you ended up posting on this forum? Want to make sure I don't have my forum link wires crossed somewhere. : )
