### ISSUE TITLE
Feedback for project 1

### ISSUE THREAD

**Issue by tmussa1** [susanBuck/e28-spring20#48]
Hello Professor,

Do you know how to access my feedback for project 1. I don't see anything on Canvas and wanted to know what I can improve on for project 2.

**Comment by susanBuck** [comment]
Hi Tofik,

In Canvas, if you go to [Assignments](https://canvas.harvard.edu/courses/69643/assignments) (from the menu on the left) then choose ["Week 7 Assignment (Project 1)”](https://canvas.harvard.edu/courses/69643/quizzes/164837) you should see your feedback in the comments section on the right.

If you don’t see it there, let me know.
