### ISSUE TITLE
SPA Takes more memory ?

### ISSUE THREAD

**Issue by maqboolk** [susanBuck/e28-spring20#52]
Hi All,

Since, SPA loads/switches pages dynamically without making any request to server, Will it take more time at initial load and will it take more memory? 

Thanks

**Comment by susanBuck** [comment]
They can - and this is a trade-off - potentially slower initial load, but faster interaction once the site is loaded.

Fortunately, there are ways to mitigate this, such as lazy loading and code splitting. Great article on these topics here: https://vueschool.io/articles/vuejs-tutorials/lazy-loading-and-code-splitting-in-vue-js/

Another technique is SSR or Server Side Rendering which you can read about here: 
https://ssr.vuejs.org/#what-is-server-side-rendering-ssr

**Comment by maqboolk** [comment]
Thank you.
