### ISSUE TITLE
Week 10 - Error on Product Page

### ISSUE THREAD

**Issue by guyewhite** [susanBuck/e28-spring20#55]
Hi Team,

For some reason, I cannot get my individual product page to show. I've gone through the Week 10 Part 3 video 3 times and still end up getting the same error.

Would anyone be willing to give me a hand at figuring this out?

Here is my GitHub repository: [https://github.com/guyewhite/e28/tree/master/zipfoods](https://github.com/guyewhite/e28/tree/master/zipfoods)

Here is the error I am seeing:

<img width="1096" alt="Screen Shot 2020-04-11 at 11 22 16 AM" src="https://user-images.githubusercontent.com/46040704/79051735-b81fae80-7be6-11ea-9b92-a5003317f84f.png">

<img width="544" alt="Screen Shot 2020-04-11 at 11 21 12 AM" src="https://user-images.githubusercontent.com/46040704/79051711-9cb4a380-7be6-11ea-81e9-6398f5a0c781.png">

<img width="542" alt="Screen Shot 2020-04-11 at 11 21 22 AM" src="https://user-images.githubusercontent.com/46040704/79051716-a2aa8480-7be6-11ea-8e35-fdb9767162b5.png">

**Comment by DoryAzar** [comment]
If you notice the error, the id of the product is not being passed. This is because in the main.js, you need to add « props=true » for the path definition. Otherwise, id won’t be passed as a prop. 
This should do it.

**Comment by guyewhite** [comment]
Thank you, @DoryAzar. Is there a way that I could have seen that using the information I posted above? Somehow, I missed that step in the walkthrough.

**Comment by susanBuck** [comment]
@guyewhite - 

With the error you shared, the "red flag" was the URL that was being pinged, and noting that the id portion of the url was `undefined`:

![image](https://user-images.githubusercontent.com/237711/79055524-c805b580-7c1b-11ea-9f51-0326f85c9a5d.png)

Seeing that narrows down that the id from the route segment/param was not correctly being passed. Then you'd have to do some further deduction to understand why.

For reference, here's the explanation from the notes about setting `props:true`
https://hesweb.dev/e28/notes/vue/vue-router#dynamic-route-matching-with-propstrue

(Covered in [Week 9 Part 5 video](https://www.youtube.com/embed/sJxtXKy0y38?rel=0&showinfo=0) starting at 32:00)

**Comment by guyewhite** [comment]
@susanBuck and @DoryAzar Thanks for your help in this.
