### ISSUE TITLE
How to copy an existing project

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/e28-spring20#56]
Hi everyone,

I had a good question come in from a student, wanted to share the answer here with everyone -

The question was how to copy an existing project - when they tried to build their copied project, it was returning errors.

**The trick is to remove and rebuild the `node_modules` directory in the copy to clean any caches referencing the original location.**

**Procedure:**

Copy (`zipfoods` is the source, `zipfoods-test` is the copy):
```
$ cp -r zipfoods zipfoods-test
```

Remove `node_modules` directory from the copy:
```
$ cd zipfoods-test
$ rm -rf node_modules
```

Rebuild the `node_modules directory in the copy:
```
$ npm install
```

Test that it builds:
```
/Applications/XAMPP/xamppfiles/htdocs/e28/zipfoods-test (master) ! $ npm run serve

> zipfoods@0.1.0 serve /Applications/XAMPP/xamppfiles/htdocs/e28/zipfoods-test
> vue-cli-service serve

 INFO  Starting development server...
98% after emitting CopyPlugin

 DONE  Compiled successfully in 8300ms                                                                                                                                11:22:09 AM


  App running at:
  - Local:   http://localhost:8080/ 
  - Network: http://192.168.7.27:8080/

  Note that the development build is not optimized.
  To create a production build, run npm run build.
```

**Comment by csci50-cbutler** [comment]
I am having problems with my p2 project as well.  When I power down after working on the project and then try to execute "npm run serve", it takes a long time.   Could it be a bad file, which makes sense.   I then run my zipfoods exercise and it works fine so it is leading me to believe I have a bad file.  It always hangs on an *.js file in the node_modules directory.  

Any other ideas would be very helpful.

Cecilia

**Comment by susanBuck** [comment]
@csci50-cbutler - I'm going to run your app on my machine to try and recreate.

Just to double check first - you're referring to the app `https://github.com/csci50-cbutler/e28/tree/master/zipfoods` correct?

**Comment by susanBuck** [comment]
Sorry, re-read your message and realized I misinterpreted it the first time -

Sounds like the problem is in `https://github.com/csci50-cbutler/e28/tree/master/p2` - I'll check that.

**Comment by susanBuck** [comment]
@csci50-cbutler I just tested a few times and it built reasonably fast each time. Could be something machine specific, not project specific?

When you say it takes a long time on your end, about how long are we talking? 30 seconds? 3 minutes? etc.

And just to clarify this line:

> When I power down after working on the project and then try to execute "npm run serve", it takes a long time.

So it only happens after you restart your computer?

**Comment by csci50-cbutler** [comment]
The zipfoods is working fine.  I had to restart my computer.  I am going to try my p2 file again.  The issue happened after I did my update to one of my pages late Sunday evening.  I ran the 'npm run serve' command and it hung.  

I think something i wrong with one of the files in my p2/nodes_module directories as that is where it hangs all the time.  It seems to be on a *.js file.  I will try again tonight and take some screen shots.

Cecilia

**Comment by csci50-cbutler** [comment]
I just ran it on my p2 project again.  I think there is something wrong with the change I made with one of the pages yesterday.  Here is the screen shot.  

```
c:\xampp\htdocs\e28\p2 (master -> origin) $ npm run serve

> p2@0.1.0 serve c:\xampp\htdocs\e28\p2
> vue-cli-service serve

 INFO  Starting development server...
40% building 89/103 modules 14 active c:\xampp\htdocs\e28\p2\node_modules\strip-ansi\index.js
c:\xampp\htdocs\e28\p2 (master -> origin) $ npm run serve
```

It hangs on that index.js file.  On occasion it gets to 90/103 modules.  

Cecilia

**Comment by csci50-cbutler** [comment]
I am going to create a new issue for this.  I reverted back to a previous page.  It has to be the new changes that is causing the problem.

**Comment by susanBuck** [comment]
One thing to try is deleting/rebuilding your `node_modules` directory:

```bash
$ rm -rf node_modules
$ npm install
```
