### ISSUE TITLE
npm install running slow

### ISSUE THREAD

**Issue by csci50-cbutler** [susanBuck/e28-spring20#57]
I moved my issue from Issue #56.  I thought it was the same, but turns out it was not quite the same.  I made a copy of my p2 project and deleted the node_modules folder and when I would execute npm run serve, it would still hang.  Some steps I took:
1)  I a reverted back to the old ".vue" page I had before.  It ran fine.  That let me know there was an issue with my updated page.
2)  I used an embedded map and graph in the template.  Apparently it had inline `<style></style>` tags within the template.  

Once I moved that into the style section, it worked.  I still have other errors but I have a functioning project again. See portion of the template below to show the inline style tags: 

```html
<h2>North America Geos</h2>
      <div class="mapouter">
          <div class="gmap_canvas">
          <iframe width="600" height="500" id="gmap_canvas"
                  src="https://maps.google.com/maps?q=north%20america&t=&z=13&ie=UTF8&iwloc=&output=embed"
                  frameborder="0" scrolling="no" marginheight="0" marginwidth="0">
          </iframe>
          <a href="https://www.embedgooglemap.org">google. maps directions</a>
          </div>
          <style>.mapouter{position:relative;text-align:right;height:500px;width:600px;}.gmap_canvas {overflow:hidden;background:none!important;height:500px;width:600px;}</style>
      </div>

```

3)  I also forgot to include links and scripts in my /public/index.html file for the map and graphs.  However, that did not cause the hanging.  Once I removed the inline styles, I was able to receive errors and output that helped me work through the errors,

I will check a few more items and close this out.

**Comment by susanBuck** [comment]
Hi @csci50-cbutler - Thanks for the update and notes on your troubleshooting process. Reverting to previous working states and comparing the differences is always a useful approach to narrowing down a problem. 👍

**Comment by susanBuck** [comment]
Going to close this thread, but feel free to re-open or start a new thread if there are any related issues.
