### ISSUE TITLE
A Wise Approach to Filtering?

### ISSUE THREAD

**Issue by guyewhite** [susanBuck/e28-spring20#58]
Hi Team,

@susanBuck 's api.js file in Zipfoods has been a great start toward that which I need to employ as the bulk of the work for my project 2. I was even able to add a way by which to order the list of products as follows...

```js
async all(collection) {
        let results = {};
        const querySnapshot = await this.api
            .collection(collection)
            .orderBy("name").get();
        querySnapshot.forEach(doc => {
            results[doc.id] = doc.data();
        });
        return results;
    }
```

_Notice the ".orderBy" in there._

**My question: Where is a good starting point for me to be able to be able to allow the user to choose how to filter the results of such a query?**

I'll have at least 30 documents in firebase with about 7-10 key/value pairs that I need users to be able to filter by.

I need it to work as follows:

**Phase 1:**

_From all documents in the database..._

User Selections Option A ----> Filter By Option A
_or_
User Selections Option B ----> Filter by Option B

**Phase 2:**

_Only from the remaining documents from Phase 1..._

User Selections Option C ----> Further Filter By Option C
_or_
User Selections Option D ----> Further Filter by Option D

**Phase 3:**

_Only from the remaining documents from Phase 3..._

User Selections Option E ----> Further Filter By Option E
_or_
User Selections Option F ----> Further Filter by Option F

**My initial thoughts** are that are that there has to be a way to apply multiple filters at the same time... but I don't know where to start there. Any thoughts or clues?

**Comment by susanBuck** [comment]
Hi @guyewhite -

**Suggested approach: Do the first level filtering against the API, then the subsequent filtering on those results.**

To facilitate this, I suggest adding a new method to `api.js` that allows for filtering:

```js
/**
 * 
 */
async filter(collection, field, operator, value) {
    try {
        const querySnapshot = await this.api.collection(collection).where(field, operator, value).get();
        return querySnapshot.docs;
    }
    catch (error) {
        return 'Error getting documents: ' + error;
    }
}
```

Once that exists, here's an example where I use it to filter (1) all products costing more than $4 and (2) weigh less than 1lb and (3) are perishable:

```js
// 1st level filter against the API
app.api.filter('products', 'price', '>', 4).then(results => {
    console.log('1st filter: products costing more than $4:', results);

    // 2nd level filter against the results from the API
    results = _.filter(results, result => {
        return result.data().weight < 1;
    });
    console.log('2nd filter: ...and weighing less than 1lb:', results);

    // 3rd level filter
    results = _.filter(results, result => {
        return result.data().perishable;
    });
    console.log('3rd filter: ...and is perishable:', results);
});
```

Note that the above example utilizes [lodash](https://lodash.com/) to help with the filtering.

To use in your project, import lodash:

```
$ npm install lodash 
```

And import it in whatever file you use it in:
```
let _ = require('lodash');
```

Let me know if you have any questions about the above, or if I missed the mark on what you're trying to accomplish. : )

**Comment by guyewhite** [comment]
@susanBuck , my naive thinking is that I might apply a series of v-if statements to do the secondarily filtering. In my current approach, I am offering one question at a time to do the filtering. However, another implementation could offer them many checkboxes at once. **_Does Vue offer a more streamlined approach for the filtering where multiple filters can be applied simultaneously?_**

For example, when shopping online, one might only want to select certain brands of clothing, while not seeing the results for others:

X Adias
X Nike
_ Puma
_Schwin

**Comment by susanBuck** [comment]
I think for that you're actually looking more at functionality within the Firestorm SDK/API than functionality within Vue.

For example, check out: https://firebase.google.com/docs/firestore/query-data/queries#in_and_array-contains-any

```
citiesRef.where('country', 'in', ['USA', 'Japan']);
```

In your example, "country" would be "brand" and the array `['USA', 'JAPAN']` would be the array of values from your brand checkboxes.

I'd suggest expanding on my api.js example to make it work for you - similar to how I suggested the `filter` in function above, you could create a `filterIn` function.

**Comment by guyewhite** [comment]
Thanks again, @susanBuck !

**Comment by angyts** [comment]
Wow @susanBuck , this is really some cool javascript magic.
