### ISSUE TITLE
VStudio code may not open in Catalina

### ISSUE THREAD

**Issue by vthil3049** [susanBuck/e28-spring20#6]
I'm running on MacOS Catalina and had an issue opening VS Code where it said:
**“Visual Studio Code” can’t be opened because Apple cannot check it for malicious software**
Solution was to open it thru 'Settings and Privacy' option -> 'Open Anyway' as described here:

https://github.com/microsoft/vscode/issues/74782

**Comment by guyewhite** [comment]
Thanks, @vthil3049

Similarly, you can follow the following procedure:

- In the Finder on your Mac, locate the app you want to open. ...
- Control-click the app icon, then choose Open from the shortcut menu.
- Click Open.

This will bypass the security lock down in most cases.
