### ISSUE TITLE
Opportunities to make up for lost points 

### ISSUE THREAD

**Issue by tmussa1** [susanBuck/e28-spring20#62]
Hello All,

This semester has been a problem with having to adjust to working from home due to the current crisis. I have lost points here and there because of not having enough time to manage everything. Is it possible to get our lowest grade dropped or to maybe complete a makeup assignment?

**Comment by susanBuck** [comment]
Hi @tmussa1,

I shared a note regarding accommodations for the Corona virus a couple weeks ago which you can reference here: https://github.com/susanBuck/e28-spring20/issues/32

Why don't you drop me an email at susanbuck@fas.harvard.edu and we can discuss. 

(Same note to anyone else reading this thread - don't hesitate to reach out.)

Susan
