### ISSUE TITLE
Computed Functions in CategoriesPage & ShowFeatured error when using Firebase

### ISSUE THREAD

**Issue by procchio77** [susanBuck/e28-spring20#63]
I went ahead replaced the seed products from the ShowFeatured component to use firebase api.  Once I did that vue throws an error that this.products.filter is not a function.  Same issue on the CategoriesPage. 

A life-cycle issue with mounted & computed?

**Comment by maqboolk** [comment]
@procchio77 

Please look at this **closed** forum. it might help you.

Zipfoods - CategoriesPage.vue #60

**Comment by procchio77** [comment]
I feel dumb, thanks!
