### ISSUE TITLE
Does image name with spaces cause issue?

### ISSUE THREAD

**Issue by maqboolk** [susanBuck/e28-spring20#66]
Hi All,
I am trying to load an image that have spaces in their names. will it cause issue in rendering?
I am trying to find  an image with the the data from api that have spaces in it.

**Comment by maqboolk** [comment]
yes, image name with spaces does cause issue.
I renamed the image name and removed all spaces it resolved the issue

**Comment by susanBuck** [comment]
Glad you got it sorted out. And just to confirm - I would not recommend using spaces in image or file names. Might work in certain contexts, but will create issues in others.
