### ISSUE TITLE
Requirements for project 2 -- "All links clickable"

### ISSUE THREAD

**Issue by angyts** [susanBuck/e28-spring20#67]
Dear Professor @susanBuck ,

Regarding project 2, can I hand in "unfinished" work, the links are clickable.. But there might not be "real" functions attached to them yet.

For example: "You are on the login page" , or "under construction for some function not built yet".

Also, can I leave "TODO" in the code base for things that I will come back to build later, but are beyond the current requirements?

**Comment by csci50-cbutler** [comment]
I am in a similar situation.  I have all the pages coming up using the vue-router.  1 page is not fully developed.  It has an under construction message with a countdown timer.  The countdown timer is using a vue component..

Cecilia

**Comment by susanBuck** [comment]
@punggolzenith Absolutely. : )
