### ISSUE TITLE
Possible cors issues

### ISSUE THREAD

**Issue by tmussa1** [susanBuck/e28-spring20#68]
I have not deployed my app in production yet but do you think I will be facing some cross site scripting issues when I do?

**Comment by ambielecki** [comment]
Are you hitting your own API or something someone else has deployed like Firebase? Something like Firebase should have an open cors policy and no problems.  Something you deployed, then yes you could run into cors issues unless you've opened it up on the backend (I did this for p2, I'm hitting my own API on a separate subdomain and had to open up the cors permissions to my e28p2 site and make sure it was accepting the correct headers) .

**Comment by susanBuck** [comment]
👍to @ambielecki's notes.

**Comment by susanBuck** [comment]
Closing this issue as I believe the question has been addressed, but feel free to keep the discussion going or re-open if you have any pending questions.
