### ISSUE TITLE
Helpful Resource for Seeding Database + Question

### ISSUE THREAD

**Issue by guyewhite** [susanBuck/e28-spring20#70]
@susanBuck in the Week 10 lecture provided an admin page for seeding one's database.

If you are "visual" like me, inputting data into a text editor for seeding is not always the best solution for creating initial data for the database. I use a tool called [Zoho Creator]( https://www.zoho.com/creator/) for a lot of my research activities. You can create a visual form and then input data there. Afterwards, you can export to a JSON file and then seed the database. I found this [article helpful ](https://medium.com/lucas-moyer/how-to-import-json-data-into-firestore-2b370486b622)for that. 

**Question**: Is there an easier way to upload the data from a JSON file to seed the database than the approach covered in this [article](https://medium.com/lucas-moyer/how-to-import-json-data-into-firestore-2b370486b622)? **Specifically, notice how you have to input the individual variable names**, which is a major pain when I start changing variable names around as I further develop this SPA:

```js
menu.forEach(function(obj) {
    db.collection("menu").add({
        id: obj.id,
        name: obj.name,
        description: obj.description,
        price: obj.price,
        type: obj.type
    }).then(function(docRef) {
        console.log("Document written with ID: ", docRef.id);
    })
    .catch(function(error) {
        console.error("Error adding document: ", error);
    });
});
```

I imagine there is a much more artful way to do this, like @susanBuck 's add function -- which I would have used it it could accept the JSON formatting that my software tool uses.

**Comment by susanBuck** [comment]
Hi @guyewhite - The two links to articles in your post are pointing to `https://www.zoho.com/creator` - Can you correct that/let me know what articles you're referring to?

**In regards to easier ways to import JSON data:**

In terms of default functionality, Firebase's _Cloud Firestore_ falls short here, IMO. If you look at their other database type, *Realtime Database*, there's an option from the console to import JSON data:

![image](https://user-images.githubusercontent.com/237711/79778075-2f9bbf00-8306-11ea-8f60-3ee4b1258c92.png)

The same can not be said for Cloud Firestore.

Similarly, the Firebase command line tool, [firebase-tools](https://github.com/firebase/firebase-tools#realtime-database-commands) has [commands for Realtime Database](https://github.com/firebase/firebase-tools#realtime-database-commands) like `database:set` and `database:update` that lets you specify a data file. 

Compare that to [their Cloud Firestore commands](https://github.com/firebase/firebase-tools#cloud-firestore-commands), and no such similar options exist.

Did a little digging though, and found a package to help with seeding Firestore that you might find useful: https://www.npmjs.com/package/firestore-seed.

**Comment by guyewhite** [comment]
Hi @susanBuck Thanks for the reply. Here is the article I was referring to (links updated in my original post too): [https://medium.com/lucas-moyer/how-to-import-json-data-into-firestore-2b370486b622](https://medium.com/lucas-moyer/how-to-import-json-data-into-firestore-2b370486b622)

I was successful in seeding the database with this solution -- but, as mentioned in the original post, it's not quick and easy at all. **For sure, the import JSON feature in Realtime Database would be really great with Firebase if that option was available.**

**Comment by susanBuck** [comment]
You could adapt the example seed code I used (`AdminPage.vue`) to import from a .json file instead of a .js file.

Example...

First, import a products.json file:
```
let productSeeds = require('@/seeds/products.json');
```

(Here's an example [products.json](https://gist.github.com/susanBuck/0de05b99d5ef8c162ab0f406ba0cd5af) file if you want to test this out)

Then update setting the `products` collections to point to `productSeeds.products`: 

```js
data: function() {
        return {
            message: '',
            collections: {
                products: productSeeds.products
            }
        };
    },
```

The `seedApi` method stays exactly the same.

I think this achieves what you want - which is not having to hard-code the variable/property names and instead have it dynamically pulled from the JSON data.

**Comment by guyewhite** [comment]
OMG @susanBuck , thank you! This totally will save me so much time as I finish out the database contents side of this.
