### ISSUE TITLE
Independent Study Implementation Required in Project 3?

### ISSUE THREAD

**Issue by guyewhite** [susanBuck/e28-spring20#72]
Hi @susanBuck ,

As I'm working on finalizing my independent study assignment, I'm curious: Are we **_required_** to implement whatever we discuss in our Independent Study in our Project 3? 

Your answer will help me decide how I want to go about finishing both the independent study assignment, as well as Project 3.

Thanks!

**Comment by susanBuck** [comment]
Hi @guyewhite - Nope, it's not required you implement whatever you cover in your independent study in Project 3.

**Comment by guyewhite** [comment]
Thank you!!
