### ISSUE TITLE
v-cloak not working for conditionally rendering error message

### ISSUE THREAD

**Issue by tmussa1** [susanBuck/e28-spring20#73]
Hello All,

My app renders an error message that I don't want rendered during preloading. I have tried putting v-cloak on the root but it doesn't seem to work.

In the root - <div v-cloak>
Then in css - 
[v-cloak] {
  display: none !important;
}

**Comment by susanBuck** [comment]
Hi @tmussa1 -

Can you update your latest code in Github and share your repository? It'll be easier to help you troubleshoot if we can see the full picture. 

Susan

**Comment by tmussa1** [comment]
Here is my repo. https://github.com/tmussa1/p2. The section that is unnecessarily shown is when navigating from the homepage towards the game. It looks like the call to the external API is taking time to populate the hints and thus showing the error. I had that call in the created() life cycle hook. Please let me know if there is a better life cycle hook than that

**Comment by susanBuck** [comment]
Hi @tmussa1 - Thanks for sharing your repo - I was able to clone locally to test and see what you're describing.


You are correct that the delay from getting the data from the API is causing the error message to show.

From the docs on [`v-cloak`](https://vuejs.org/v2/api/#v-cloak), it notes that v-cloak is only on the element until the instance finishes compilation:

> This directive will remain on the element until the associated Vue instance finishes compilation.

In your case, the component is compiled and *then* the API call is made.

To address it, I suggest adding a data property, something like `dataLoaded` that's initialized to `false`.

Then, when the API call is done, toggle it to `true`:

```js
axios({
                method: 'GET',
                url:
                    'https://wordsapiv1.p.rapidapi.com/words/' +
                    this.randomWord,
                headers: {
                    'content-type': 'application/octet-stream',
                    'x-rapidapi-host': 'wordsapiv1.p.rapidapi.com',
                    'x-rapidapi-key': process.env.VUE_APP_WORD_API_KEY
                }
            })
                .then(response => {
                    this.dataLoaded = true; // # <----- TOGGLE TO TRUE
                    // [...etc...]
                })
                .catch(error => {
                    console.log(error);
                });
```

Then you can use this to conditionally display the error only if `dataLoaded` is true (i.e. if the API call is complete:

```html
<b-card-text v-if='dataLoaded && !hintone && !hinttwo && !hintthree' class='hints'>
```

Let me know if you have any follow-up questions about the above.

**Comment by tmussa1** [comment]
That helped solved the problem. Thank you

**Comment by maqboolk** [comment]
@susanBuck 

Can i mix Scsss and css in same script? 

something like this
```
<style lang='scss'>
@import './assets/scss/p2.scss';
[v-cloak] {
  display: none;
}
li {
   display: inline-block;
}
</style>
```

**Comment by susanBuck** [comment]
Yup - You can mix CSS and SCSS in the same style block, assuming that style block has the lang set to `scss`.

If it doesn't, any SCSS code won't be correctly interpreted and you'd be limited to just CSS.

**Comment by maqboolk** [comment]
@susanBuck  Thank you
