### ISSUE TITLE
Update regarding covid-19 extensions & a note about this week's lecture videos

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/e28-spring20#74]
Hi everyone,

I'm writing with a quick check-in as we approach the final weeks of the semester, and some notes on adjustments I'm making due to the covid-19 situation. 

**First**, I'll be waiving late penalties for **all students** for:
+ Week 11 Assignment (due this Thursday at midnight)
+ Week 12 Assignment
+ Week 13 Assignment

Week 14 still has a hard deadline of Thu May 14th because it's the end of the semester. 

You should still aim to complete these assignments by their due dates to not get behind, but if that's not possible you can submit within the +7 day late window without the -5 point deduction.

**Second**, I will be making an adjustment to the third and final project of the semester, making the authorization component optional. I will share some information on authorization for those who have the time to explore it, but I will not be covering it in lecture nor requiring it on P3. Stay tuned for the full details of P3 which I'll be posting and talking about as part of this week's lecture.

**Finally**, a preemptive note to let you know that I may not have this week's lecture's posted by the usual time of Thu @ 8pm. A bug (hopefully not "the" bug) has hit my household that has had me up much of the past few nights, and it's catching up on me such that I anticipate not being able to complete this week's lecture recordings/edits on time. If that happens, I will have them posted some time Thursday night or Friday. I apologize for this delay, and hope it does not complicate anyone's schedules too much.

I know this has been a tough semester for a lot of us, and I wish everyone strength and good thoughts as we power through the end. I hope the above accommodations ease some of your burdens, and as always - if you need any additional assistance with the material/completing assignments/etc., don't hesitate to reach out to me here or directly (susanbuck@fas.harvard.edu).

**Comment by angyts** [comment]
😱 😱 😱 

Yes, stay safe, hopefully it is not *the bug*.

**Comment by vthil3049** [comment]
Oh, no! Wishing you and your family a speedy recovery, Susan! Thanks for your note.

**Comment by maqboolk** [comment]
Take care

**Comment by DoryAzar** [comment]
Thank you. Stay well and safe.

**Comment by BrendanJohn** [comment]
Thank you for the update, wishing you and your family a quick recovery.

**Comment by RobertHolzhauser** [comment]
Thank you Susan.  Be well.

**Comment by smaaliki** [comment]
Thank you Susan. Stay safe and I hope for a speedy recovery for your hosuehold.

**Comment by guyewhite** [comment]
Hi @susanBuck ! So sorry to hear about the bug going through your home! Please take the time you need to get better and take care of fam!

Regarding authorization, do you think you’ll have enough info in the lecture or optional reading to help me at least get that API key unexposed? I want to deploy my application to my clients and I can’t do that unless I can do that step. Please let me know.

Thanks for your help. Please take care.

**Comment by susanBuck** [comment]
@guyewhite - Yes, will for sure get the API key unexposed this week! 👍

**Comment by MatthewCaulkins** [comment]
Thank you Susan, hope you and the family all get better soon.

**Comment by csci50-cbutler** [comment]
Please stay safe and I hope it is not the bug either.  Just stay well as some people get it when their health declines. 

Thank you for the updates on the schedule changes.  I am hoping to still get everything done on time but it has been challenging.

Cecilia
