### ISSUE TITLE
Data is not going to the collection which was manually created

### ISSUE THREAD

**Issue by oscarxiao** [susanBuck/e28-spring20#75]
I am using the same snippet of code from the professor's instruction to add some sample data in Firebase. The newly created data actually go to a new collection. Does anyone have a similar issue? 
<img width="753" alt="Screen Shot 2020-04-22 at 9 46 34 PM" src="https://user-images.githubusercontent.com/40640721/80060512-a0e49900-84e3-11ea-85ff-7f2c64fcd4b3.png">
<img width="751" alt="Screen Shot 2020-04-22 at 9 47 59 PM" src="https://user-images.githubusercontent.com/40640721/80060532-a80ba700-84e3-11ea-9c0d-1587e69edcaf.png">
<img width="622" alt="Screen Shot 2020-04-22 at 9 49 25 PM" src="https://user-images.githubusercontent.com/40640721/80060546-ac37c480-84e3-11ea-8f1c-7268157312a7.png">

**Comment by oscarxiao** [comment]
I want to also add one more point:

I couldn't "read" the data that was manually created in the Firebase console either.

**Comment by smaaliki** [comment]
Hi Oscar. Do you have two collections with the same name "allExperiments"?

**Comment by susanBuck** [comment]
That's quite odd - I don't understand how two collections could have the same ID. If I go into the console and try and manually create a new collection with the same ID, it ends up just adding the new document within the existing collection of that same name. 

@oscarxiao Is your code on Github up to date? I'd like to clone your work locally to test/debug on my end.

**Comment by oscarxiao** [comment]
Hi, @smaaliki ,I manually created the first collection in Firebase console, then I used ".add" method and tried to add a new document into the same collection. That's why the collection names are the same.

**Comment by oscarxiao** [comment]
Hi @susanBuck, I manually created the first collection in Firebase console, then I used ".add" method and tried to add a new document into the same collection. Aren't they supposed to be the same id? That's why we could add document under the same collection, right? I just pushed it to [my github](https://github.com/oscarxiao/e28/tree/master/p2)

**Comment by smaaliki** [comment]
Hi.  I just tried to add a space at the end of my collection's name in the code and a new collection was created.  Maybe when you created the collection manually it had an extra space at the end (or vice versa)? If you click on the edit icon next to the collection's name in firebase (see image below), you can check if you have the same issue.
![image](https://user-images.githubusercontent.com/35793409/80280480-4f235500-8715-11ea-921a-217667dd29de.png)

**Comment by oscarxiao** [comment]
Hi @smaaliki, Thank you! problem solved!
---
> Hi. I just tried to add a space at the end of my collection's name in the code and a new collection was created. Maybe when you created the collection manually it had an extra space at the end (or vice versa)? If you click on the edit icon next to the collection's name in firebase (see image below), you can check if you have the same issue.
> ![image](https://user-images.githubusercontent.com/35793409/80280480-4f235500-8715-11ea-921a-217667dd29de.png)
