### ISSUE TITLE
Property not defined

### ISSUE THREAD

**Issue by maqboolk** [susanBuck/e28-spring20#8]
Hi All,

I keep on getting this error in console. 
`vue.js:634 [Vue warn]: Property or method "startList" is not defined on the instance but referenced during render.`

for some reason it is not finding startList in the .js file. following is my .js code. 

```
let app = new Vue({
    el: "#app",
    data: {
        startList: true,
        item: '',
        items: [],
    }
}) 
```

and in inspector -> sources i don't see the same. I see following.

```
let app = new Vue({
    el: "#app",
    data: {
        item: "",
        items: []
    }
})

```

Please let me know if anyone have any solution for it. 
Thanks

**Comment by ambielecki** [comment]
Is this a recent change to your js file?  The previous version may be cached in the browser.  You can do a hard refresh to reload all sources or try opening your page up in an incognito window.

**Comment by maqboolk** [comment]
Hi Andrew,

it is working now. clearing the cache helped.

thank you

**Comment by susanBuck** [comment]
Good catch @ambielecki! 

Couple tips to avoid the dreaded "cache bug" when developing:

**Tip 1**
Most browsers have a keyboard shortcut that will refresh the page and clear the cache; this is sometimes referred to has a "hard refresh". 

For example, on my Mac/Chrome if I hold down just `cmd` + `r` it does a regular refresh, but if I do `shift` + `cmd` + `r` it refreshes and clears the cache. 

I find this helpful whenever I'm working with CSS/JavaScript where browsers could be caching outdated code. 

(Google "hard refresh" and your browser/OS to find the shortcut for your system.)

**Tip 2**
Most browsers also have an option in their dev tools to automatically clear the cache whenever the page is refreshed *if* the dev tools is open. For example, here's that option in Chrome's dev tools:

![image](https://user-images.githubusercontent.com/237711/74693268-0dc47580-51b9-11ea-8a8f-fc1681187721.png)
