### ISSUE TITLE
P3 Question: Will We Need A TLS Certificate?

### ISSUE THREAD

**Issue by ambielecki** [susanBuck/e28-spring20#83]
I took a quick preview of getting an app on Netlify and noticed that they have a semi-automated process for setting up a wildcard certificate through Lets Encrypt.  This will most likely be a problem with the domain I am using as I have a certificate issued on my DO server.  Just wanted to make sure we won't be needing tls / https for p3 (not a big deal, I'd just grab a fresh domain name).

Thanks

**Comment by susanBuck** [comment]
Nope, HTTPS won't be required for P3. That being said, I will talk about HTTPS this week as it relates to Netlify and Apache (but it will remain optional for the project)
