### ISSUE TITLE
How to get a "copy" of Vuex Product Store

### ISSUE THREAD

**Issue by guyewhite** [susanBuck/e28-spring20#86]
Hi Team,

Part of my implementation is to make a "copy" of the Vuex data such that I can further filter it down.

What I want to do is something like this:

```js
mounted: function() {
        this.tests = allTests;
    },
    computed: {
        allTests: function() {
            return this.$store.state.tests;
        }
    }
```

**How can I make a copy of the tests from the store on page load such that I can further filter them down?**

**Comment by susanBuck** [comment]
FYI - Working up an example of this now; will reply again shortly.

**Comment by susanBuck** [comment]
One way you could do this is define another computed property that is dependent on the `alltests` computed property. Then, when `allTests` is loaded, it will trigger your second computed property to load.

Here's an example (using sorting instead of filtering, but - same idea):

```js
computed: {
    products: function() {
        return this.$store.state.products;
    },
    sortedProducts: function() {
        let sorted = {};
        for (let key of Object.keys(this.products)) {
            if (this.products[key].perishable) {
                sorted[key] = this.products[key];
            }
        }
        return sorted;
    }
}
```

**Comment by guyewhite** [comment]
@susanBuck, thank you for your response and help. I was able to get my code to work using this as a guide. However, to be clear, what I want to do is simple and I simply can't find a simple way of doing it.

Upon initial page load, I want my page-specific array "tests" to be a copy of the computed property allTests. This way, I can use lodash to filter down what I have in "tests."

An easy fix for this was to create a function, activated by a button, that simply makes a copy of allTests:

`this.tests = this.allTests;`

**Is there some way I can do this on page load?** The challenge is that I can't put it in mounted as that creates all sorts of hell for some reason. I've done a lot of searching. What I want is for the computed properties to have enough time to load.... and then for my copy above to be made. I've been looking at the diagram below to understand when in the lifecycle each of these things is happening to see an opportunity of where I could get this going (and how). Any guidance?

![lifecycle](https://user-images.githubusercontent.com/46040704/80892005-9ca34300-8c7c-11ea-8708-98296df8fc15.png)

**Comment by susanBuck** [comment]
Hi @guyewhite -

The delay of your *tests* data loading is not specific to/dependent on the lifecycle events of the Vue application - **it's dependent on the request to the API being complete**. 

In order to make a copy of *tests*, you have to wait and make sure *tests* exist.

There are two ways to do this:

First - via a computed property as I showed above. Make a CP that is dependent on tests, so that when tests is available, you can access its data.

Second - via a watcher - set a watcher on products that triggers when products changes. Example:

```js
export default {
    data: function() {
        return {
            productsCopy: {}
        };
    },
    computed: {
        products: function() {
            return this.$store.state.products;
        }
    },
    watch: {
        // This fires when `products` changes
        products: function() {
            this.productsCopy = this.products;
        }
    }
};
```

**Comment by guyewhite** [comment]
@susanBuck, thank you so much for your help on this. This did it. Thank you.
