### ISSUE TITLE
Function inside "mounted" won't run

### ISSUE THREAD

**Issue by oscarxiao** [susanBuck/e28-spring20#87]
Hi Guys, 
I tried to show all data together using "app.api.all" inside methods, but it seems the function won't run and there is an extra error in my console. Does anyone have any idea? 
<img width="516" alt="Screen Shot 2020-04-30 at 12 50 01 PM" src="https://user-images.githubusercontent.com/40640721/80753032-72694e00-8ae1-11ea-866a-b2489578ea23.png">
<img width="709" alt="Screen Shot 2020-04-30 at 12 52 44 PM" src="https://user-images.githubusercontent.com/40640721/80753096-8ad96880-8ae1-11ea-9669-3348d817974a.png">

**Comment by susanBuck** [comment]
FYI Cloning your code locally to debug now; will reply again when I have more details.

**Comment by susanBuck** [comment]
`getAllExperiments` is a method, so when invoking it, you have to include parenthesis. 

So instead of:

```js
this.getAllExperiments;
```

It should be:
```js
this.getAllExperiments();
```

Let me know if after making the above change you're still getting the errors in the console (they weren't there in my tests).

**Comment by oscarxiao** [comment]
Thank you, @susanBuck . It works now.
----
> `getAllExperiments` is a method, so when invoking it, you have to include parenthesis.
> 
> So instead of:
> 
> ```js
> this.getAllExperiments;
> ```
> 
> It should be:
> 
> ```js
> this.getAllExperiments();
> ```
> 
> Let me know if after making the above change you're still getting the errors in the console (they weren't there in my tests).

**Comment by susanBuck** [comment]
@oscarxiao Excellent!

And just to be sure - no more errors in the console?

**Comment by oscarxiao** [comment]
@susanBuck ,the error started showing up when I was trying to fix problem of chart.js in #82, It stop just moment ago. I don't know why. I don't think I changed anyting significant code in between

**Comment by susanBuck** [comment]
Hm, odd. Well, if it pops up again, create a new post. : )
