### ISSUE TITLE
Section Meetings

### ISSUE THREAD

**Issue by csci50-cbutler** [susanBuck/e28-spring20#9]
Does this course have a TA and section meetings?  Just wondering if I missed any..

Cecilia

**Comment by susanBuck** [comment]
Hi Cecilia,

Nope, no section meetings. All Q&A happens via the forum. Additionally, students are welcome/encouraged to reach out to me directly if you want to set up a time to connect 1 on 1 via screenshare to ask questions, go over material, troubleshoot, etc.
