### ISSUE TITLE
Drag and Drop Feature

### ISSUE THREAD

**Issue by angyts** [susanBuck/e28-spring20#90]
I am working on some kind of a roster and scheduler. You can see it [live at this link.](https://p2.paulang.rocks/day)

As you can see, now I have to click on a "shift" then click on the "staff" to schedule them.

I would like to make it even nicer by adding drag and drop, for example, drag the "staff" to the "shift", then let it "become" scheduled on the shift then show the staff on the shift.

I'm actually using some Vuetify calendar components to display these areas.

Does anyone have any idea how I can implement something like this?

**Comment by susanBuck** [comment]
There are packages that can help with this - for example:
https://www.npmjs.com/package/vuedraggable

More options here: https://www.npmjs.com/search?q=vue%20drag%20drop

**Comment by susanBuck** [comment]
Closing this out, but feel free to keep the discussion going or start a new thread if you have any issues implementing a drag and drop package.
