### ISSUE TITLE
Different between local server and production server!

### ISSUE THREAD

**Issue by oscarxiao** [susanBuck/e28-spring20#91]
Hi Everyone, 
My website is showing different appearance between local server and production server. 
After I make sure my website is locally served right. Then I pushed to my github. 
In the server, I pull from github under e28 directory and 
go into my p2 directory and 
run "npm install --production" "service apache2 restart" 
Does anybody have any idea? 
<img width="700" alt="Screen Shot 2020-05-01 at 4 20 26 PM" src="https://user-images.githubusercontent.com/40640721/80848340-cb131680-8bc7-11ea-841b-214a01b63bd3.png">
<img width="555" alt="Screen Shot 2020-05-01 at 4 20 37 PM" src="https://user-images.githubusercontent.com/40640721/80848346-d1a18e00-8bc7-11ea-83a7-254ea79ea701.png">

**Comment by DoryAzar** [comment]
yes you need to also do 'npm run build' to get dist file that packages everything. This might be the reason.

**Comment by oscarxiao** [comment]
@DoryAzar, Yes , I did. I tried that too. I also tried to delete the whole e28 directory and re-clone it again. It doesn't work.

**Comment by DoryAzar** [comment]
Did you create a virtual host on the server that points to the p3/dist folder?

**Comment by susanBuck** [comment]
@oscarxiao What's the URL to your app on production?

**Comment by oscarxiao** [comment]
@DoryAzar , yes, I did. 
> Did you create a virtual host on the server that points to the p3/dist folder?

**Comment by oscarxiao** [comment]
@susanBuck , my url for prodution is e28p2.oscarate28.me. I just looked again. It finally shows the right thing. I just don't get it. I tried it so many times yesterday and it just won't show.
---
> @oscarxiao What's the URL to your app on production?

**Comment by susanBuck** [comment]
@oscarxiao Glad it's working now. It appears the primary differences in the screenshots you shared was styling/CSS specific - I'm guessing it was a browser cache issue.
