### ISSUE TITLE
P3 Question: Will instructor need / want to run app locally?

### ISSUE THREAD

**Issue by ambielecki** [susanBuck/e28-spring20#93]
Another quick question.  My p3 application depends on my own api, which in production has a limited set of domains allowed in its CORS policy. This would currently preclude running the app and tests locally (I am using a local build of the api that does allow local hosts for testing).  Do you want the ability to do this (ie, should I open up the CORS policy as it is really just a test app anyway) and should build instructions for setting the .env files be included?

Thanks

**Comment by ambielecki** [comment]
Nevermind, just saw in the video that you will, will make sure the prod api supports localhosts

**Comment by susanBuck** [comment]
Yup - just confirming that I will test locally.

I will primarily do this to run tests. I may also do it if I need to debug something, or want to show a student some alternative way to code something as part of the project feedback.
