### ISSUE TITLE
[Firebase] Client access to your Cloud Firestore database expiring in [x] day(s)

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/e28-spring20#94]
FYI: You will soon receive an email from Firebase with the subject `[Firebase] Client access to your Cloud Firestore database expiring in [x] day(s)`.

This will happen because in Week 9 when we set up our Firebase projects, our Firestore database was set with this default/testing security rule:

```js
rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {

    // This rule allows anyone on the internet to view, edit, and delete
    // all data in your Firestore database. It is useful for getting
    // started, but it is configured to expire after 30 days because it
    // leaves your app open to attackers. At that time, all client
    // requests to your Firestore database will be denied.
    //
    // Make sure to write security rules for your app before that time, or else
    // your app will lose access to your Firestore database
    match /{document=**} {
      allow read, write: if request.time < timestamp.date(2020, 5, 8);
    }
  }
}
```

You can see/edit this rule within the Firebase console > *Database* > *Rules*.

As the comments note in this rule, it makes our API data open for a period of 30 days. 

We are now approaching that 30 day mark, so your data will soon be locked down, which would cause your applications to stop working as expected as your API calls get rejected. To quickly address, you can simply bump the timestamp up on the security rule (e.g. change ` timestamp.date(2020, 5, 8)` to ` timestamp.date(2020, 6, 8))`.

**Later today, I'll be posting bonus information on authentication which gets into writing a less liberal and more useful security rule.**

In the meantime, though, I just wanted to make a quick post about this as some of you might get an email from Firebase alerting you to the fact that the "test" period is coming to an end soon.

**Comment by susanBuck** [comment]
Update: Auth info has now been posted: #95

**Comment by maqboolk** [comment]
@susanBuck Is there any limit on how many times I can update security rule ?

**Comment by susanBuck** [comment]
@maqboolk - Nope!

**Comment by sahil352005** [comment]
my plan is expired what can i do now?
