### ISSUE TITLE
getting a specific document from Vuex state

### ISSUE THREAD

**Issue by maqboolk** [susanBuck/e28-spring20#97]
Hi All,

Is it possible to to get specific document using Vuex -> state -> array of products?
I want to find a specific document without calling an api that is available in api.js.

I don't want to use this api but want to retrieve a specific docuement.
```javascript
    /**
     * Get a document from a `collection` where `field` == `value`
     * ex: get('products', 'slug', 'bare-coconut-chips')
     */
    async find(collection, field, value) {
        try {
            const querySnapshot = await this.api.collection(collection).where(field, "==", value)
                .get();
            return querySnapshot.docs.shift().data();
        }
        catch (error) {
            return 'Error getting documents: ' + error;
        }
    }
```

Thanks

**Comment by susanBuck** [comment]
Hi @maqboolk - I think what you're describing is similar to the Vuex getter I created, `getProductBySlug` in that it lets me query the existing product data for a specific product?

Ref: https://github.com/susanBuck/e28/blob/master/zipfoods/src/common/store.js#L40

If you're thinking of something else, let me know and I can work up another example for you.

**Comment by maqboolk** [comment]
@susanBuck Thank you for pointing out to me about getter. I'll try and let you know if it worked for me.

**Comment by maqboolk** [comment]
@susanBuck 
Getter is working perfectly. 
Thank you
